disabled_rules:
  - dynamic_inline
  - empty_parentheses_with_trailing_closure
  - private_unit_test
  - type_body_length
  - valid_docs
  - nesting

identifier_name:
  excluded:
    - id
    - ok

excluded:
  - Pods
